### ISSUE TITLE
ReferenceError: SSHClient is not defined

### ISSUE THREAD

**Issue by andrewnaumann** [mivaecommerce/api-sdk-node#1]
Node v14.4.0
api-sdk-node v 2.0.0

I receive this error when importing merchantapi

`const api = require("merchantapi");`

My terminal logs the following error

`
App threw an error during load
ReferenceError: SSHClient is not defined
    at Object.<anonymous> (/Users/andrew/Developement/CBIM-2/node_modules/merchantapi/src/index.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/andrew/Developement/CBIM-2/main.js:8:13)
`

I've been using this api successfully for 6 months with version 1.3.0. I'm in need of upgrading my store and this app to be Miva 10 compatible. I'm happy to provide any additional info you may need to track down if this is a bug.

**Comment by ghassani** [comment]
Hi Andrew

Thanks for letting us know. I have filed this issue in our internal bug tracker. We have a new version coming out that fixes some other issues so I will be able to get this fix out in the next patch verison.

**Comment by ghassani** [comment]
If you want a workaround in the meantime you can just change line 8 of index.js in the package from

`const { Client }             = require('./client');`

to

`const { Client, SSHAgent, SSHAgentClient }             = require('./client');`

**Comment by ghassani** [comment]
Fixed in release 2.0.1
